
import {createLocalizedPathnamesNavigation} from 'next-intl/navigation';
import {locales} from './i18n-config';

// The `pathnames` object holds pairs of internal
// and external paths, separated by locale.
export const pathnames = {
  // If all locales use the same path, use the special '*' locale
  '/': '/',
  '/about': '/about',
  '/admin': '/admin',
  '/admin/content': '/admin/content',
  '/admin/reports': '/admin/reports',
  '/agri-events': '/agri-events',
  '/agri-events/create': '/agri-events/create',
  '/ai-assistant': '/ai-assistant',
  '/auth/forgot-password': '/auth/forgot-password',
  '/auth/recover': '/auth/recover',
  '/auth/reset-password': '/auth/reset-password',
  '/auth/signin': '/auth/signin',
  '/auth/signup': '/auth/signup',
  '/blog': '/blog',
  '/careers': '/careers',
  '/community-guidelines': '/community-guidelines',
  '/contact': '/contact',
  '/farm-management': '/farm-management',
  '/farm-management/asset-management': '/farm-management/asset-management',
  '/farm-management/asset-management/create': '/farm-management/asset-management/create',
  '/farm-management/inventory': '/farm-management/inventory',
  '/farm-management/inventory/create': '/farm-management/inventory/create',
  '/farm-management/create-farm': '/farm-management/create-farm',
  '/farm-management/family-farm': '/farm-management/family-farm',
  '/farm-management/farms': '/farm-management/farms',
  '/farm-management/financials': '/farm-management/financials',
  '/farm-management/financials/apply': '/farm-management/financials/apply',
  '/farm-management/financials/log': '/farm-management/financials/log',
  '/farm-management/fgw-guide': '/farm-management/fgw-guide',
  '/farm-management/knf-inputs': '/farm-management/knf-inputs',
  '/farm-management/labor': '/farm-management/labor',
  '/farm-management/seed-starting': '/farm-management/seed-starting',
  '/fi/applications': '/fi/applications',
  '/fi/products': '/fi/products',
  '/fi/products/create': '/fi/products/create',
  '/forums': '/forums',
  '/forums/create': '/forums/create',
  '/groups': '/groups',
  '/groups/create': '/groups/create',
  '/help-center': '/help-center',
  '/industry-news': '/industry-news',
  '/insurance': '/insurance',
  '/insurance/apply': '/insurance/apply',
  '/insurance/products': '/insurance/products',
  '/insurance/products/create': '/insurance/products/create',
  '/marketplace': '/marketplace',
  '/marketplace/create': '/marketplace/create',
  '/marketplace/create-shop': '/marketplace/create-shop',
  '/marketplace/my-purchases': '/marketplace/my-purchases',
  '/marketplace/my-sales': '/marketplace/my-sales',
  '/marketplace/promotions': '/marketplace/promotions',
  '/messages': '/messages',
  '/network': '/network',
  '/network/agent-tools': '/network/agent-tools',
  '/network/my-network': '/network/my-network',
  '/pinboard': '/pinboard',
  '/privacy': '/privacy',
  '/search': '/search',
  '/settings': '/settings',
  '/sustainability': '/sustainability',
  '/talent-exchange': '/talent-exchange',
  '/terms': '/terms',
  '/traceability': '/traceability',
  '/wallet': '/wallet',

  // Dynamic routes
  '/agri-events/[id]': '/agri-events/[id]',
  '/agri-events/[id]/manage': '/agri-events/[id]/manage',
  '/blog/[slug]': '/blog/[slug]',
  '/farm-management/asset-management/[assetId]/edit': '/farm-management/asset-management/[assetId]/edit',
  '/farm-management/inventory/[itemId]/edit': '/farm-management/inventory/[itemId]/edit',
  '/farm-management/farms/[farmId]': '/farm-management/farms/[farmId]',
  '/farm-management/farms/[farmId]/create-crop': '/farm-management/farms/[farmId]/create-crop',
  '/farm-management/farms/[farmId]/crops/[cropId]': '/farm-management/farms/[farmId]/crops/[cropId]',
  '/farm-management/farms/[farmId]/crops/[cropId]/edit': '/farm-management/farms/[farmId]/crops/[cropId]/edit',
  '/farm-management/farms/[farmId]/crops/[cropId]/log-harvest': '/farm-management/farms/[farmId]/crops/[cropId]/log-harvest',
  '/farm-management/farms/[farmId]/crops/[cropId]/log-input-application': '/farm-management/farms/[farmId]/crops/[cropId]/log-input-application',
  '/farm-management/farms/[farmId]/crops/[cropId]/log-observation': '/farm-management/farms/[farmId]/crops/[cropId]/log-observation',
  '/farm-management/farms/[farmId]/edit': '/farm-management/farms/[farmId]/edit',
  '/farm-management/labor/[workerId]': '/farm-management/labor/[workerId]',
  '/fi/applications/[id]': '/fi/applications/[id]',
  '/forums/[topicId]': '/forums/[topicId]',
  '/forums/[topicId]/create-post': '/forums/[topicId]/create-post',
  '/forums/[topicId]/[postId]': '/forums/[topicId]/[postId]',
  '/groups/[groupId]': '/groups/[groupId]',
  '/groups/[groupId]/create-post': '/groups/[groupId]/create-post',
  '/groups/[groupId]/manage': '/groups/[groupId]/manage',
  '/groups/[groupId]/posts/[postId]': '/groups/[groupId]/posts/[postId]',
  '/insurance/[productId]': '/insurance/[productId]',
  '/marketplace/[id]': '/marketplace/[id]',
  '/marketplace/[id]/manage-service': '/marketplace/[id]/manage-service',
  '/marketplace/shops/[shopId]': '/marketplace/shops/[shopId]',
  '/profiles/[id]': '/profiles/[id]',
  '/profiles/[id]/edit': '/profiles/[id]/edit',
  '/traceability/batches/[batchId]': '/traceability/batches/[batchId]',
} satisfies Pathnames<typeof locales>;

export const {Link, redirect, usePathname, useRouter, getPathname} =
  createLocalizedPathnamesNavigation({
    locales,
    pathnames,
  });
